---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: timesample
  name: timesample
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 30080
  selector:
    app: timesample
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: timesample
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: timesample
    spec:
      containers:
      - name: spring-boot-timesample
        image: jaimegag/spring-boot-timesample  #change me 
        ports:
        - containerPort: 8080
